export type screenName =
  | 'Userselection'
  | 'Login'
  | 'Signup'
  | 'Patientonbordingfirst'
  | 'Patientonbordingsecond'
  | 'Patientonbordingthird'
  | 'Doctoronbordingfirst'
  | 'Doctoronbordingsecond'
  | 'Doctoronbordingthird'
  | 'Userdashboard'
  | 'Home'
  | 'Doctors'
  | 'Appointments'
  | 'Profile'
  | 'Patientbottomnavigation'
  | 'Medical';
